### ISSUE TITLE
If we create a wall in the usual way, an error appears

### ISSUE THREAD

**Issue by kaiwas** [paullee0/FreeCAD_SketchArch#17]
Even if the SketchArch workbench is not loaded, an error occurs when creating a regular wall.

Video demonstration

https://github.com/user-attachments/assets/68092b0a-04ce-4827-9ace-185fdb661443

Code in the python console
`16:29:41  pyException: Traceback (most recent call last):
  File "/home/kaiwas/.local/share/FreeCAD/Mod/FreeCAD_SketchArch/ArchWall.py", line 323, in execute
    propSetSelectedNameCur = baseProxy.getPropertySet(obj.Base,
                             ^^^^^^^^^
<class 'UnboundLocalError'>: cannot access local variable 'baseProxy' where it is not associated with a value
16:29:41  ArchSketch__NAME: 'FeaturePython' object has no attribute 'AttachToAxisOrSketch'
16:29:41  Wall: cannot access local variable 'baseProxy' where it is not associated with a value`

Version
`OS: Manjaro Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38843 (Git) AppImage
Build type: Release
Branch: main
Hash: d519f24df9931e4a98d19ee39cdcd6124ae6a7bd
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Russian/Russia (ru_RU)
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Qt default
Installed mods: 
  * OpenTheme 2024.9.1
  * FreeCAD_SketchArch
  * PitchedRoof
  * lattice2 1.0.0
`

**Comment by paullee0** [comment]
Thanks, got the problem now, would fix it soon :)

**Comment by paullee0** [comment]
Commit d4568c26bf116520376f2bde110d7648585d54de should fix this :)

**Comment by kaiwas** [comment]
> Pls report if the bug is fixed, would close this issue then, thanks.

Yes. Everything works!
