### ISSUE TITLE
Please add description to README.md

### ISSUE THREAD

**Issue by luzpaz** [paullee0/FreeCAD_SketchArch#2]
Even if this project isn't complete, it would be nice to know what you're doing :smile:

**Comment by paullee0** [comment]
Thanks for comment.  Will learn how to do it :)

**Comment by luzpaz** [comment]
I can fix the markdown for you. If you just add 
Short Description  
(screenshot)  
About  
Prerequisites  
Install  
Usage  
Feedback  
(FC thread)  
License

**Comment by paullee0** [comment]
Thanks!  Will do!

**Comment by paullee0** [comment]
Jogging down some previous and latest thoughts

**Comment by paullee0** [comment]
Had added README.md and updated for quite a while.

Good to close this ?

Thanks.

**Comment by paullee0** [comment]
Thanks !  This looks like to me a python exercise and thanks mentoring :D

Merry Christmas and Happy New Year 2022 !
