### ISSUE TITLE
SketchArch takes control even if it is not loaded.

### ISSUE THREAD

**Issue by kaiwas** [paullee0/FreeCAD_SketchArch#20]
If SketchArch is installed in the system, but is in the list of NOT loaded workbenches - the program works as if this workbench is active. (Sketches have a corresponding name, and in the properties of objects all SketchArch settings are active)
As a result, in order to return to the standard method of work, I have to delete ArchSketch. I have done this several dozen times) This is very annoying and completely destroys the desire to experiment. There must be a simple way to completely turn off SketchArch without deleting it, if it is not needed.

Video demonstration.

https://github.com/user-attachments/assets/db57eb14-3a43-4796-a43a-d6faa1c33130

The ideal option is the ability to turn off SketchArch at any time directly in the workbench. So that all objects that would be created when the workbench is turned off would have standard properties. In this case, it would be possible to combine approaches within one document.
Some objects would work according to the SketchArch method, and some in the standard way.

PS / You need to go beyond your workbench more often ;)

**Comment by paullee0** [comment]
Added a toggle button ArchSketchLock as discussed in -
https://forum.freecad.org/viewtopic.php?t=50802&start=220#p790057

**Comment by paullee0** [comment]
ArchSketchLock enable/disable automatic use of ArchSketch
ArchSketchData enable/disable use of base ArchSketch's properties set and enable/disable features

Closing this issue at the moment
