### ISSUE TITLE
 offsetWire() got an unexpected keyword argument 'wireNedge'

### ISSUE THREAD

**Issue by gianlucafiore** [paullee0/FreeCAD_SketchArch#21]
I get the following error when I want to use the plugin
![image](https://github.com/user-attachments/assets/b8b56432-5c46-4f79-931b-b467fea46fd6)

Absolutely everything is broken FreeCAD
![image](https://github.com/user-attachments/assets/7f873026-61f6-4b53-87b8-c6d67acfa89c)

![image](https://github.com/user-attachments/assets/257da8b3-2aa0-4ec6-9130-69ef4d29535e)
Even common sketches break

**Comment by paullee0** [comment]
@gianlucafiore  The updated ArchWall.py requires another 2 files below - https://github.com/FreeCAD/FreeCAD/pull/17496
- intersections.py
- offsets.py

They are uploaded in the [SketArch github](https://github.com/paullee0/FreeCAD_SketchArch) now.

Download them and restart FreeCAD to try.  If there is still problem, may need to move to the ... usr/Mod/Draft/draftgeoutils folder (backup the original files first)

**Comment by gianlucafiore** [comment]
@paullee0 The problem persists either way, I can't fix it

**Comment by paullee0** [comment]
Any error messagec?

**Comment by paullee0** [comment]
Would help to debug if error message is reported, in the meantime, you may download the previous ArchWall.py version at link below, thanks :-

https://github.com/paullee0/FreeCAD_SketchArch/blob/d4568c26bf116520376f2bde110d7648585d54de/ArchWall.py

**Comment by gianlucafiore** [comment]
> Any error messages?

yes, sory, throw the same error

**Comment by gianlucafiore** [comment]
> Would help to debug if error message is reported, in the meantime, you may download the previous ArchWall.py version at link below, thanks :-
> 
> https://github.com/paullee0/FreeCAD_SketchArch/blob/d4568c26bf116520376f2bde110d7648585d54de/ArchWall.py

I'm going to try this

**Comment by paullee0** [comment]
> > Any error messages?
> 
> yes, sory, throw the same error
> 

It seems Windows does not find the intersection.py and offset.py, can you replace the original installation version ?

**Comment by gianlucafiore** [comment]
> EDIT - Need to restart FreeCAD after replacing

Yes, I did indeed have to reset all the software by default

**Comment by paullee0** [comment]
No problem. the intersection.py and offset.py were merged in stock FreeCAD and hope there is less problem.

Closing this now.
